### ISSUE TITLE
Syntax error in Lab5-Predicate Pushdown

### ISSUE THREAD

**Issue by a140262** [aws-samples/redshift-immersionday-labs#5]
Query Execution Error in Lab5-Predicate Pushdown: 
[Amazon](500310) Invalid operation: syntax error at or near ")" Position: 517;

Correct SQL Script:

SELECT c.c_name, c.c_mktsegment, t.prettyMonthYear, uv.totalRevenue
FROM (
  SELECT customer, visitYearMonth, SUM(adRevenue) as totalRevenue 
  FROM clickstream.uservisits_parquet1
  WHERE customer <= 3 and visitYearMonth >= 199810
  GROUP BY  customer, visitYearMonth) as uv
RIGHT OUTER JOIN customer as c ON c.c_custkey = uv.customer
INNER JOIN (
  SELECT DISTINCT d_yearmonthnum, (d_month||','||d_year) as prettyMonthYear 
  `FROM dwdate WHERE d_yearmonthnum >= 199810) as t ON uv.visitYearMonth = t.d_yearmonthnum`
ORDER BY c.c_name, c.c_mktsegment, uv.visitYearMonth ASC;

**Comment by rjvgupta** [comment]
This has been resolved.  Thanks for bringing it to my attention.
