### ISSUE TITLE
Lab4 mentions about us-west-2 for the first time

### ISSUE THREAD

**Issue by vaidykal** [aws-samples/redshift-immersionday-labs#9]
Hi,

It may be better to update the README.md file or Lab-1 instructions to indicate that the Redshift Cluster has to be launched in the us-west-2 region.

Lab-4 states an assumption that the Redshift cluster has been created in us-west-2, whereas the cluster was created in Lab-1 (which does not mention the same). 

Please update!!

Thanks,
Vaidy

**Comment by rjvgupta** [comment]
Labs have been moved.
